### ISSUE TITLE
Unable to start Robe properly

### ISSUE THREAD

**Issue by ikunali** [ypresto/robe-atom#2]
It's trying to start robe & it seems robe got started too, but then it displays error message for Robe launch timeout
## Console log:

robePath: H:\tmp\robe
robe.coffee:30 launchTimeout: 20000
/H:/a/packages/robe/lib/robe-runner.coffee:143 Using 'ruby -Ilib' to start robe for 'H:\'. robePath: H:\tmp\robe
/H:/a/packages/robe/lib/robe-runner.coffee:36 Starting robe...
/H:/a/packages/robe/lib/robe-runner.coffee:39 Got stdout from robe process: '"robe on 62077"
'.
robe-runner.coffee:48 Uncaught (in promise) Error: Robe launch timedout after waiting 20000 msecs, was wating for '"robe on"'.(…)(anonymous function) @ robe-runner.coffee:48
robe-runner.coffee:48 Uncaught (in promise) Error: Robe launch timedout after waiting 20000 msecs, was wating for '"robe on"'.(…)(anonymous function) @ robe-runner.coffee:48
robe-runner.coffee:48 Uncaught (in promise) Error: Robe launch timedout after waiting 20000 msecs, was wating for '"robe on"'.(…)(anonymous function) @ robe-runner.coffee:48
robe-runner.coffee:48 Uncaught (in promise) Error: Robe launch timedout after waiting 20000 msecs, was wating for '"robe on"'.(…)(anonymous function) @ robe-runner.coffee:48
robe-runner.coffee:48 Uncaught (in promise) Error: Robe launch timedout after waiting 20000 msecs, was wating for '"robe on"'.(…)(anonymous function) @ robe-runner.coffee:48
robe-runner.coffee:48 Uncaught (in promise) Error: Robe launch timedout after waiting 20000 msecs, was wating for '"robe on"'.(…)

**Comment by ypresto** [comment]
> Got stdout from robe process: '"robe on 62077"

It seems robe server is launched correctly.
Which versions of robe and robe-atom are you using?

**Comment by ikunali** [comment]
Yes, robe server is getting started, however, robe-atom still says timed out & hence I don't get any auto-complete suggestions

Robe: 0.7.9
robe-atom: 0.3.0
Atom: 1.5.3

**Comment by dgutov** [comment]
@TG-KK Does it take longer to start up than 20 seconds, maybe?
