### ISSUE TITLE
This plugin includes the go to definition ability?

### ISSUE THREAD

**Issue by sadhu89** [ypresto/robe-atom#5]

**Comment by ypresto** [comment]
Currently it is not implemented yet but I want to include it..!

**Comment by ypresto** [comment]
Sorry but I'm going to use vscode instead of Atom. It's pretty faster, and also offers powerful completion..!
Below plugin (although buggy for now) provides go to definition feature.
https://github.com/rubyide/vscode-ruby

(UPDATE: Maybe better alternative: https://github.com/castwide/solargraph)
