### ISSUE TITLE
Unable to execute robe launcher when not a rails project

### ISSUE THREAD

**Issue by jonyeezs** [ypresto/robe-atom#6]
I'm getting this error:
```
Got stdout from robe process: 'bundler: command not found: C:\Users\Jonathan\.atom\packages\robe\bin\robe_launcher.rb
Install missing gem executables with `bundle install`
'.  robe-runner.coffee:32

Error: Robe process exited with code 127.(…)   robe-runner.coffee:64 
```

I believe this is because bundle exec is trying to run robe_launcher.rb which isn't an executable.

setting  [robe-runner:117](https://github.com/ypresto/robe-atom/blob/master/lib/robe-runner.coffee#L117) to `when 'bundler'  then 'bundle exec ruby'` seems to work for me.

I'm not entirely sure if is the reason why I'm getting the error (kinda new to ruby). So I'd like to see what you would have to say.

**Comment by ypresto** [comment]
Unfortunately I moved from Atom to VSCode, and am archiving this repo. Anyway thanks for reporting the issue!
